/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "analysis": {
        "messages": {
            "evaluated": string;
            "history": string;
            "no_credits": string;
            "cv_required": string;
            "cv_unreadable": string;
            "invalid_pdf": string;
            "file_too_large": string;
            "job_required": string;
            "session_required": string;
            "session_not_found": string;
        };
    };
    "auth": {
        "messages": {
            "registered": string;
            "logged_in": string;
            "profile": string;
        };
        "errors": {
            "email_taken": string;
            "invalid_credentials": string;
            "unauthorized": string;
            "token_expired": string;
            "forbidden": string;
            "inactive_account": string;
        };
    };
    "common": {
        "common": {
            "errors": {
                "internal_server_error": string;
                "bad_request": string;
                "payment_required": string;
            };
        };
    };
    "users": {
        "messages": {
            "profile": string;
            "list": string;
            "credits_granted": string;
            "subscription_updated": string;
        };
        "errors": {
            "not_found": string;
        };
    };
    "validation": {
        "required": string;
        "string": string;
        "email": string;
        "array": string;
        "number": string;
        "uuid": string;
        "boolean": string;
        "min": string;
        "max": string;
        "enum": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
