/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "analysis": {
        "messages": {
            "evaluated": string;
            "history": string;
            "no_credits": string;
            "cv_required": string;
            "cv_unreadable": string;
            "invalid_pdf": string;
            "file_too_large": string;
            "job_required": string;
            "session_required": string;
            "session_not_found": string;
        };
    };
    "common": {
        "validation": {
            "required": string;
            "string": string;
            "email": string;
            "array": string;
            "number": string;
            "uuid": string;
            "boolean": string;
            "min": string;
        };
        "candidates": {
            "messages": {
                "created": string;
                "list": string;
                "detail": string;
                "updated": string;
                "deleted": string;
                "not_found": string;
            };
        };
        "jobs": {
            "messages": {
                "created": string;
                "list": string;
                "detail": string;
                "updated": string;
                "deleted": string;
                "not_found": string;
            };
        };
        "parser": {
            "messages": {
                "parse_success": string;
                "no_raw_text": string;
            };
        };
        "matching": {
            "messages": {
                "evaluated": string;
                "top_candidates": string;
                "candidate_matches": string;
            };
        };
        "common": {
            "errors": {
                "internal_server_error": string;
                "bad_request": string;
                "payment_required": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
